spring:
  application:
    name: stayhub

  datasource:
    url: jdbc:postgresql://localhost:5432/stayhub
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

