CREATE TABLE users
(
    id            UUID PRIMARY KEY     DEFAULT gen_random_uuid(),
    email         VARCHAR(255)         NOT NULL,
    password_hash VARCHAR(255)         NOT NULL,
    full_name     VARCHAR(100)         NOT NULL,
    phone         VARCHAR(20)          NOT NULL,
    avatar_url    VARCHAR(255),
    status        VARCHAR(20)          NOT NULL DEFAULT 'pending',
    is_deleted    BOOLEAN              NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ          NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ          NOT NULL DEFAULT now(),

    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_phone UNIQUE (phone),
    CONSTRAINT ck_users_email_normalized
        CHECK (email = lower(btrim(email))),
    CONSTRAINT ck_users_status
        CHECK (status IN ('active', 'inactive', 'pending', 'banned'))
);

CREATE TABLE roles
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_key    VARCHAR(50)  NOT NULL,
    role_name   VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_roles_role_key UNIQUE (role_key)
);

CREATE TABLE permissions
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_key  VARCHAR(100) NOT NULL,
    permission_name VARCHAR(150) NOT NULL,
    description     VARCHAR(255),
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_permissions_permission_key UNIQUE (permission_key)
);

CREATE TABLE user_roles
(
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID        NOT NULL,
    role_id     INTEGER     NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_user_roles_user_role UNIQUE (user_id, role_id),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE INDEX idx_user_roles_role_id
    ON user_roles (role_id);

CREATE TABLE role_permissions
(
    role_id       INTEGER NOT NULL,
    permission_id INTEGER NOT NULL,

    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role
        FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission
        FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE
);

CREATE INDEX idx_role_permissions_permission_id
    ON role_permissions (permission_id);

INSERT INTO roles (role_key, role_name, description)
VALUES ('CUSTOMER', 'Customer', 'Có thể tìm kiếm và đặt phòng khách sạn'),
       ('HOTEL_OWNER', 'Hotel Owner', 'Có thể quản lý các khách sạn thuộc sở hữu'),
       ('ADMIN', 'Administrator', 'Có thể quản trị hệ thống StayHub');

INSERT INTO permissions (permission_key, permission_name, description)
VALUES ('USER_READ', 'Read users', 'Có thể xem thông tin tài khoản người dùng'),
       ('USER_STATUS_UPDATE', 'Update user status', 'Có thể kích hoạt, vô hiệu hóa hoặc khóa người dùng'),
       ('USER_ROLE_UPDATE', 'Update user roles', 'Có thể gán hoặc thu hồi vai trò của người dùng'),
       ('ROLE_READ', 'Read roles', 'Có thể xem vai trò và các quyền thuộc vai trò');

INSERT INTO role_permissions (role_id, permission_id)
SELECT role.id, permission.id
FROM roles AS role
CROSS JOIN permissions AS permission
WHERE role.role_key = 'ADMIN'
  AND permission.permission_key IN (
    'USER_READ',
    'USER_STATUS_UPDATE',
    'USER_ROLE_UPDATE',
    'ROLE_READ'
  );
